/**
 * Sentinel Audit — Markdown Reporter
 * Outputs a human-readable Markdown report with severity badges.
 */

const fs = require('fs');
const path = require('path');

const SEVERITY_ORDER = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'];

const SEVERITY_BADGES = {
  CRITICAL: '![CRITICAL](https://img.shields.io/badge/-CRITICAL-red?style=flat-square)',
  HIGH: '![HIGH](https://img.shields.io/badge/-HIGH-orange?style=flat-square)',
  MEDIUM: '![MEDIUM](https://img.shields.io/badge/-MEDIUM-yellow?style=flat-square)',
  LOW: '![LOW](https://img.shields.io/badge/-LOW-blue?style=flat-square)',
  INFO: '![INFO](https://img.shields.io/badge/-INFO-lightgrey?style=flat-square)',
};

const SEVERITY_EMOJI = {
  CRITICAL: '🔴',
  HIGH: '🟠',
  MEDIUM: '🟡',
  LOW: '🔵',
  INFO: '⚪',
};

/**
 * Sort findings by severity.
 */
function sortFindings(findings) {
  return [...findings].sort((a, b) => {
    const ai = SEVERITY_ORDER.indexOf(a.severity);
    const bi = SEVERITY_ORDER.indexOf(b.severity);
    return ai - bi;
  });
}

/**
 * Summarize findings by severity.
 */
function summarize(findings) {
  const summary = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
  for (const f of findings) {
    const key = f.severity.toLowerCase();
    if (summary[key] !== undefined) summary[key]++;
  }
  return summary;
}

/**
 * Generate a Markdown report.
 * @param {object} params
 * @param {string} params.target - Target URL or directory
 * @param {Array} params.findings - Array of all findings
 * @param {Date|string} [params.scanDate] - Scan timestamp
 * @param {string} [params.outputPath] - Optional path to write file
 * @returns {string} Markdown report string
 */
function generate({ target, findings, scanDate, outputPath }) {
  const sortedFindings = sortFindings(findings);
  const summary = summarize(findings);
  const date = scanDate ? new Date(scanDate).toISOString() : new Date().toISOString();

  const lines = [];

  // Header
  lines.push('# 🔍 Sentinel Audit Report\n');
  lines.push(`**Scan Date:** ${date}  `);
  lines.push(`**Target:** \`${target}\`  `);
  lines.push(`**Total Findings:** ${findings.length}\n`);

  // Summary table
  lines.push('## 📊 Summary\n');
  lines.push('| Severity | Count |');
  lines.push('|----------|-------|');
  lines.push(`| 🔴 CRITICAL | ${summary.critical} |`);
  lines.push(`| 🟠 HIGH | ${summary.high} |`);
  lines.push(`| 🟡 MEDIUM | ${summary.medium} |`);
  lines.push(`| 🔵 LOW | ${summary.low} |`);
  lines.push(`| ⚪ INFO | ${summary.info} |`);
  lines.push('');

  if (summary.critical > 0 || summary.high > 0) {
    const urgent = summary.critical + summary.high;
    lines.push(`> ⚠️ **Attention required:** ${urgent} critical/high severity finding(s) need immediate review.\n`);
  }

  // Findings
  lines.push('## 🔎 Detailed Findings\n');

  if (sortedFindings.length === 0) {
    lines.push('*No findings recorded.*\n');
  } else {
    for (let i = 0; i < sortedFindings.length; i++) {
      const f = sortedFindings[i];
      const emoji = SEVERITY_EMOJI[f.severity] || '⚪';
      const badge = SEVERITY_BADGES[f.severity] || '';

      lines.push(`### ${i + 1}. ${emoji} ${f.severity} — ${f.title} ${badge}\n`);
      lines.push(`**Description:** ${f.description}\n`);
      if (f.cwe && f.cwe !== 'N/A') {
        lines.push(`**CWE:** \`${f.cwe}\`\n`);
      }
      lines.push(`**Remediation:** ${f.remediation}\n`);
      lines.push('---\n');
    }
  }

  // Footer
  lines.push('## ℹ️ About This Report\n');
  lines.push('This report was generated by **Sentinel Audit** — a CLI pre-penetration-test security audit tool.\n');
  lines.push('Severity ratings follow the standard: CRITICAL > HIGH > MEDIUM > LOW > INFO.\n');
  lines.push('Each finding includes a CWE (Common Weakness Enumeration) reference for tracking and remediation.\n');

  const markdown = lines.join('\n');

  if (outputPath) {
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(outputPath, markdown, 'utf-8');
  }

  return markdown;
}

module.exports = { generate };
